"""create event store tables

Revision ID: e87257d5adb8
Revises: 
Create Date: 2026-02-13 17:36:37.556977

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'e87257d5adb8'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('event_store',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('aggregate_id', sa.UUID(), nullable=False),
    sa.Column('aggregate_type', sa.String(length=100), nullable=False),
    sa.Column('aggregate_version', sa.Integer(), nullable=False),
    sa.Column('event_type', sa.String(length=255), nullable=False),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('event_metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('aggregate_version > 0', name='ck_event_store_version_positive'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('aggregate_id', 'aggregate_version', name='uq_event_store_aggregate_version')
    )
    op.create_index('ix_event_store_aggregate_order', 'event_store', ['aggregate_id', 'aggregate_version'], unique=False)
    op.create_table('outbox',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('aggregate_id', sa.UUID(), nullable=False),
    sa.Column('aggregate_type', sa.String(length=100), nullable=False),
    sa.Column('event_type', sa.String(length=255), nullable=False),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('event_metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('processed', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_outbox_unprocessed', 'outbox', ['processed'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_outbox_unprocessed', table_name='outbox')
    op.drop_table('outbox')
    op.drop_index('ix_event_store_aggregate_order', table_name='event_store')
    op.drop_table('event_store')
    # ### end Alembic commands ###
